# script de uniformización ------------------------------------------------
filtro <- function(df){
  df %>% 
    filter(!UNIDADES %in% c("", "-", "UNIDADES", NA)) %>% arrange(PARAMETROS) %>% 
    mutate(PARAMETROS = case_when(
      PARAMETROS %in% c("Aceites y grasas") ~ "Aceites y Grasas",
      PARAMETROS %in% c("Alcalinidad") ~ "Alcalinidad",
      PARAMETROS %in% c("Aluminio (Al tot)","Aluminio total (Al tot)") ~ "Aluminio",
      PARAMETROS %in% c("Nitrógeno amoniacal", "Nitrógeno amoniacal (N-NH3)") ~ "Amoniaco-N",
      PARAMETROS %in% c("Antimonio (Sb tot)","Antimonio total (Sb tot)") ~ "Antimonio",
      PARAMETROS %in% c("Arsénico (As tot)", "Arsénico total (As tot)") ~ "Arsénico",
      PARAMETROS %in% c("Bario (Ba tot)", "Bario total (Ba tot)") ~ "Bario",
      PARAMETROS %in% c("Berilio (Be tot)", "Berilio total (Be tot)") ~ "Berilio",
      PARAMETROS %in% c("Bicarbonatos") ~ "Bicarbonatos",
      PARAMETROS %in% c("Bismuto", "Bismuto Total") ~ "Bismuto",
      PARAMETROS %in% c("Boro (B tot)", "Boro total (B tot)") ~ "Boro",
      PARAMETROS %in% c("Cadmio (Cd tot)", "Cadmio total (Cd tot)") ~ "Cadmio",
      PARAMETROS %in% c("Calcio (Ca tot)", "Calcio total (Ca tot)") ~ "Calcio",
      PARAMETROS %in% c("Carbonatos") ~ "Carbonatos",
      PARAMETROS %in% c("Cianuro libre") ~ "Cianuro Libre",
      PARAMETROS %in% c("Cianuro WAD ") ~ "Cianuro WAD",
      PARAMETROS %in% c("Cloruros") ~ "Cloruros",
      PARAMETROS %in% c("Cobalto (Co tot)", "Cobalto total (Co tot)") ~ "Cobalto",
      PARAMETROS %in% c("Cobre (Cu tot)", "Cobre total (Cu tot)") ~ "Cobre",
      PARAMETROS %in% c("Coliformes Termotolerantes", "Coliformes termotolerantes ") ~ "Coliformes Termotolerantes",
      PARAMETROS %in% c("Coliformes totales") ~ "Coliformes Totales",
      PARAMETROS %in% c("Conductividad", "Conductividad ", "Conductividad (Cond,)") ~ "Conductividad",
      PARAMETROS %in% c("Cromo (Cr tot)", "Cromo total (Cr tot)") ~ "Cromo Total",
      PARAMETROS %in% c("Demanda Bioq, de Oxígeno ", "Demanda Bioquímica de Oxígeno", "Demanda Bioquímica de Oxígeno ") ~ "Demanda Bioquímica de Oxígeno (DBO5)",
      PARAMETROS %in% c("Demanda Química de Oxígeno") ~ "Demanda Química de Oxígeno (DQO)",
      PARAMETROS %in% c("Escherichia coli") ~ "Escherichia coli",
      PARAMETROS %in% c("Estaño") ~ "Estaño",
      PARAMETROS %in% c("Estroncio") ~ "Estroncio",
      PARAMETROS %in% c("Fenoles") ~ "Fenoles",
      PARAMETROS %in% c("Fluoruros, F-") ~ "Fluoruros",
      PARAMETROS %in% c("Fosfatos (PO4)") ~ "Fosfatos",
      PARAMETROS %in% c("Fósforo total (P tot)", "Fósforo total)") ~ "Fósforo Total",
      PARAMETROS %in% c("Fósforo (P)") ~ "Fósforo (P)",
      PARAMETROS %in% c("Hierro (Fe tot)", "Hierro total (Fe tot)") ~ "Hierro",
      PARAMETROS %in% c("Litio (Li tot)", "Litio total (Li tot)") ~ "Litio",
      PARAMETROS %in% c("Magnesio (Mg tot)", "Magnesio total (Mg tot)") ~ "Magnesio",
      PARAMETROS %in% c("Manganeso (Mn tot)", "Manganeso (Mn)", "Manganeso total (Mn tot)") ~ "Manganeso",
      PARAMETROS %in% c("Mercurio (Hg tot)", "Mercurio total (Hg tot)") ~ "Mercurio",
      PARAMETROS %in% c("Molibdeno") ~ "Molibdeno",
      PARAMETROS %in% c("Níquel (Ni tot)", "Níquel total (Ni tot)") ~ "Niquel",
      PARAMETROS %in% c("Nitratos (NO3) ", "Nitratos (NO3)") ~ "Nitratos (NO3-)",
      PARAMETROS %in% c("Nitritos (NO2-)", "Nitritos (NO2-N)") ~ "Nitritos (NO2-)",
      PARAMETROS %in% c("Nitritos-N") ~ "Nitritos-N",
      PARAMETROS %in% c("Nitrógeno total", "Nitrógeno total (N tot,)") ~ "Nitrógeno Total",
      PARAMETROS %in% c("Oxígeno disuelto ", "Oxígeno disuelto (O2)") ~ "Oxígeno Disuelto",
      PARAMETROS %in% c("Plata (Ag tot)", "Plata total (Ag tot)") ~ "Plata",
      PARAMETROS %in% c("Plomo (Pb tot)", "Plomo total (Pb tot)") ~ "Plomo",
      PARAMETROS %in% c("Potasio (K tot)", "Potasio total (K tot)") ~ "Potasio",
      PARAMETROS %in% c("Selenio (Se tot)", "Selenio total (Se tot)") ~ "Selenio",
      PARAMETROS %in% c("Silicio") ~ "Silicio",
      PARAMETROS %in% c("Sodio (Na tot)", "Sodio total (Na tot)") ~ "Sodio",
      PARAMETROS %in% c("Sulfatos", "Sulfatos (SO4)") ~ "Sulfatos",
      PARAMETROS %in% c("Sulfuros (S2)") ~ "Sulfuros",
      PARAMETROS %in% c("Sólidos Sus, Totales", "Sólidos Suspendidos Totales") ~ "Sólidos Suspendidos Totales",
      PARAMETROS %in% c("Talio", "Talio (Ta tot)") ~ "Talio",
      PARAMETROS %in% c("Temperatura", "Temperatura (T)", "F") ~ "Temperatura",
      PARAMETROS %in% c("Titanio") ~ "Titanio",
      PARAMETROS %in% c("Uranio (U tot)", "Uranio total (U tot)") ~ "Uranio",
      PARAMETROS %in% c("Vanadio (V tot)", "Vanadio total (V tot)") ~ "Vanadio",
      PARAMETROS %in% c("Vibrio cholerae") ~ "Vibrio cholerae",
      PARAMETROS %in% c("Zinc", "Zinc total (Zn tot)") ~ "Zinc",
      PARAMETROS %in% c("pH") ~ "pH",
      TRUE ~ PARAMETROS
    ))
}